# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v1_workspace_workspace_id_trusted_ips_trusted_ip_id_patch_request import ApiV1WorkspaceWorkspaceIdTrustedIpsTrustedIpIdPatchRequest  # noqa: E501

class TestApiV1WorkspaceWorkspaceIdTrustedIpsTrustedIpIdPatchRequest(unittest.TestCase):
    """ApiV1WorkspaceWorkspaceIdTrustedIpsTrustedIpIdPatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1WorkspaceWorkspaceIdTrustedIpsTrustedIpIdPatchRequest:
        """Test ApiV1WorkspaceWorkspaceIdTrustedIpsTrustedIpIdPatchRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1WorkspaceWorkspaceIdTrustedIpsTrustedIpIdPatchRequest`
        """
        model = ApiV1WorkspaceWorkspaceIdTrustedIpsTrustedIpIdPatchRequest()  # noqa: E501
        if include_optional:
            return ApiV1WorkspaceWorkspaceIdTrustedIpsTrustedIpIdPatchRequest(
                ip_address = '',
                comment = ''
            )
        else:
            return ApiV1WorkspaceWorkspaceIdTrustedIpsTrustedIpIdPatchRequest(
                ip_address = '',
        )
        """

    def testApiV1WorkspaceWorkspaceIdTrustedIpsTrustedIpIdPatchRequest(self):
        """Test ApiV1WorkspaceWorkspaceIdTrustedIpsTrustedIpIdPatchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
