# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v1_sso_config_post_request import ApiV1SsoConfigPostRequest  # noqa: E501

class TestApiV1SsoConfigPostRequest(unittest.TestCase):
    """ApiV1SsoConfigPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1SsoConfigPostRequest:
        """Test ApiV1SsoConfigPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1SsoConfigPostRequest`
        """
        model = ApiV1SsoConfigPostRequest()  # noqa: E501
        if include_optional:
            return ApiV1SsoConfigPostRequest(
                organization_id = '',
                auth_provider = 'okta-saml',
                is_active = True,
                entry_point = '',
                issuer = '',
                cert = ''
            )
        else:
            return ApiV1SsoConfigPostRequest(
                organization_id = '',
                auth_provider = 'okta-saml',
                is_active = True,
                entry_point = '',
                issuer = '',
                cert = '',
        )
        """

    def testApiV1SsoConfigPostRequest(self):
        """Test ApiV1SsoConfigPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
