# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v1_secret_approvals_get200_response_approvals_inner_user_approvers_inner import ApiV1SecretApprovalsGet200ResponseApprovalsInnerUserApproversInner  # noqa: E501

class TestApiV1SecretApprovalsGet200ResponseApprovalsInnerUserApproversInner(unittest.TestCase):
    """ApiV1SecretApprovalsGet200ResponseApprovalsInnerUserApproversInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1SecretApprovalsGet200ResponseApprovalsInnerUserApproversInner:
        """Test ApiV1SecretApprovalsGet200ResponseApprovalsInnerUserApproversInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1SecretApprovalsGet200ResponseApprovalsInnerUserApproversInner`
        """
        model = ApiV1SecretApprovalsGet200ResponseApprovalsInnerUserApproversInner()  # noqa: E501
        if include_optional:
            return ApiV1SecretApprovalsGet200ResponseApprovalsInnerUserApproversInner(
                user_id = ''
            )
        else:
            return ApiV1SecretApprovalsGet200ResponseApprovalsInnerUserApproversInner(
                user_id = '',
        )
        """

    def testApiV1SecretApprovalsGet200ResponseApprovalsInnerUserApproversInner(self):
        """Test ApiV1SecretApprovalsGet200ResponseApprovalsInnerUserApproversInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
