# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v1_integration_auth_access_token_post_request import ApiV1IntegrationAuthAccessTokenPostRequest  # noqa: E501

class TestApiV1IntegrationAuthAccessTokenPostRequest(unittest.TestCase):
    """ApiV1IntegrationAuthAccessTokenPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1IntegrationAuthAccessTokenPostRequest:
        """Test ApiV1IntegrationAuthAccessTokenPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1IntegrationAuthAccessTokenPostRequest`
        """
        model = ApiV1IntegrationAuthAccessTokenPostRequest()  # noqa: E501
        if include_optional:
            return ApiV1IntegrationAuthAccessTokenPostRequest(
                workspace_id = '',
                integration = '',
                access_id = '',
                access_token = '',
                aws_assume_iam_role_arn = '',
                url = '',
                namespace = '',
                refresh_token = ''
            )
        else:
            return ApiV1IntegrationAuthAccessTokenPostRequest(
                workspace_id = '',
                integration = '',
        )
        """

    def testApiV1IntegrationAuthAccessTokenPostRequest(self):
        """Test ApiV1IntegrationAuthAccessTokenPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
