# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v2_workspace_workspace_id_encrypted_key_get200_response_sender import ApiV2WorkspaceWorkspaceIdEncryptedKeyGet200ResponseSender  # noqa: E501

class TestApiV2WorkspaceWorkspaceIdEncryptedKeyGet200ResponseSender(unittest.TestCase):
    """ApiV2WorkspaceWorkspaceIdEncryptedKeyGet200ResponseSender unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV2WorkspaceWorkspaceIdEncryptedKeyGet200ResponseSender:
        """Test ApiV2WorkspaceWorkspaceIdEncryptedKeyGet200ResponseSender
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV2WorkspaceWorkspaceIdEncryptedKeyGet200ResponseSender`
        """
        model = ApiV2WorkspaceWorkspaceIdEncryptedKeyGet200ResponseSender()  # noqa: E501
        if include_optional:
            return ApiV2WorkspaceWorkspaceIdEncryptedKeyGet200ResponseSender(
                public_key = ''
            )
        else:
            return ApiV2WorkspaceWorkspaceIdEncryptedKeyGet200ResponseSender(
                public_key = '',
        )
        """

    def testApiV2WorkspaceWorkspaceIdEncryptedKeyGet200ResponseSender(self):
        """Test ApiV2WorkspaceWorkspaceIdEncryptedKeyGet200ResponseSender"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
