# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v1_pki_certificates_serial_number_get200_response_certificate import ApiV1PkiCertificatesSerialNumberGet200ResponseCertificate  # noqa: E501

class TestApiV1PkiCertificatesSerialNumberGet200ResponseCertificate(unittest.TestCase):
    """ApiV1PkiCertificatesSerialNumberGet200ResponseCertificate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1PkiCertificatesSerialNumberGet200ResponseCertificate:
        """Test ApiV1PkiCertificatesSerialNumberGet200ResponseCertificate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1PkiCertificatesSerialNumberGet200ResponseCertificate`
        """
        model = ApiV1PkiCertificatesSerialNumberGet200ResponseCertificate()  # noqa: E501
        if include_optional:
            return ApiV1PkiCertificatesSerialNumberGet200ResponseCertificate(
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                ca_id = '',
                status = '',
                serial_number = '',
                friendly_name = '',
                common_name = '',
                not_before = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                not_after = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                revoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                revocation_reason = 1.337,
                alt_names = ''
            )
        else:
            return ApiV1PkiCertificatesSerialNumberGet200ResponseCertificate(
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                ca_id = '',
                status = '',
                serial_number = '',
                friendly_name = '',
                common_name = '',
                not_before = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                not_after = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testApiV1PkiCertificatesSerialNumberGet200ResponseCertificate(self):
        """Test ApiV1PkiCertificatesSerialNumberGet200ResponseCertificate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
