# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v1_integration_auth_integration_auth_id_apps_get200_response_apps_inner import ApiV1IntegrationAuthIntegrationAuthIdAppsGet200ResponseAppsInner  # noqa: E501

class TestApiV1IntegrationAuthIntegrationAuthIdAppsGet200ResponseAppsInner(unittest.TestCase):
    """ApiV1IntegrationAuthIntegrationAuthIdAppsGet200ResponseAppsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1IntegrationAuthIntegrationAuthIdAppsGet200ResponseAppsInner:
        """Test ApiV1IntegrationAuthIntegrationAuthIdAppsGet200ResponseAppsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1IntegrationAuthIntegrationAuthIdAppsGet200ResponseAppsInner`
        """
        model = ApiV1IntegrationAuthIntegrationAuthIdAppsGet200ResponseAppsInner()  # noqa: E501
        if include_optional:
            return ApiV1IntegrationAuthIntegrationAuthIdAppsGet200ResponseAppsInner(
                name = '',
                app_id = '',
                owner = ''
            )
        else:
            return ApiV1IntegrationAuthIntegrationAuthIdAppsGet200ResponseAppsInner(
                name = '',
        )
        """

    def testApiV1IntegrationAuthIntegrationAuthIdAppsGet200ResponseAppsInner(self):
        """Test ApiV1IntegrationAuthIntegrationAuthIdAppsGet200ResponseAppsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
