# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v3_secrets_batch_raw_delete_request import ApiV3SecretsBatchRawDeleteRequest  # noqa: E501

class TestApiV3SecretsBatchRawDeleteRequest(unittest.TestCase):
    """ApiV3SecretsBatchRawDeleteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV3SecretsBatchRawDeleteRequest:
        """Test ApiV3SecretsBatchRawDeleteRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV3SecretsBatchRawDeleteRequest`
        """
        model = ApiV3SecretsBatchRawDeleteRequest()  # noqa: E501
        if include_optional:
            return ApiV3SecretsBatchRawDeleteRequest(
                project_slug = '',
                workspace_id = '',
                environment = '',
                secret_path = '/',
                secrets = [
                    infisicalapi_client.models._api_v3_secrets_batch_raw_delete_request_secrets_inner._api_v3_secrets_batch_raw_delete_request_secrets_inner(
                        secret_key = '', 
                        type = 'shared', )
                    ]
            )
        else:
            return ApiV3SecretsBatchRawDeleteRequest(
                environment = '',
                secrets = [
                    infisicalapi_client.models._api_v3_secrets_batch_raw_delete_request_secrets_inner._api_v3_secrets_batch_raw_delete_request_secrets_inner(
                        secret_key = '', 
                        type = 'shared', )
                    ],
        )
        """

    def testApiV3SecretsBatchRawDeleteRequest(self):
        """Test ApiV3SecretsBatchRawDeleteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
