# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v1_password_change_password_post_request import ApiV1PasswordChangePasswordPostRequest  # noqa: E501

class TestApiV1PasswordChangePasswordPostRequest(unittest.TestCase):
    """ApiV1PasswordChangePasswordPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1PasswordChangePasswordPostRequest:
        """Test ApiV1PasswordChangePasswordPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1PasswordChangePasswordPostRequest`
        """
        model = ApiV1PasswordChangePasswordPostRequest()  # noqa: E501
        if include_optional:
            return ApiV1PasswordChangePasswordPostRequest(
                client_proof = '',
                protected_key = '',
                protected_key_iv = '',
                protected_key_tag = '',
                encrypted_private_key = '',
                encrypted_private_key_iv = '',
                encrypted_private_key_tag = '',
                salt = '',
                verifier = '',
                password = ''
            )
        else:
            return ApiV1PasswordChangePasswordPostRequest(
                client_proof = '',
                protected_key = '',
                protected_key_iv = '',
                protected_key_tag = '',
                encrypted_private_key = '',
                encrypted_private_key_iv = '',
                encrypted_private_key_tag = '',
                salt = '',
                verifier = '',
                password = '',
        )
        """

    def testApiV1PasswordChangePasswordPostRequest(self):
        """Test ApiV1PasswordChangePasswordPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
