# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v1_scim_users_org_membership_id_put_request import ApiV1ScimUsersOrgMembershipIdPutRequest  # noqa: E501

class TestApiV1ScimUsersOrgMembershipIdPutRequest(unittest.TestCase):
    """ApiV1ScimUsersOrgMembershipIdPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1ScimUsersOrgMembershipIdPutRequest:
        """Test ApiV1ScimUsersOrgMembershipIdPutRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1ScimUsersOrgMembershipIdPutRequest`
        """
        model = ApiV1ScimUsersOrgMembershipIdPutRequest()  # noqa: E501
        if include_optional:
            return ApiV1ScimUsersOrgMembershipIdPutRequest(
                schemas = [
                    ''
                    ],
                id = '',
                user_name = '',
                name = infisicalapi_client.models._api_v1_scim_users_get_200_response_resources_inner_name._api_v1_scim_Users_get_200_response_Resources_inner_name(
                    family_name = '', 
                    given_name = '', ),
                display_name = '',
                active = True
            )
        else:
            return ApiV1ScimUsersOrgMembershipIdPutRequest(
                schemas = [
                    ''
                    ],
                id = '',
                user_name = '',
                name = infisicalapi_client.models._api_v1_scim_users_get_200_response_resources_inner_name._api_v1_scim_Users_get_200_response_Resources_inner_name(
                    family_name = '', 
                    given_name = '', ),
                display_name = '',
                active = True,
        )
        """

    def testApiV1ScimUsersOrgMembershipIdPutRequest(self):
        """Test ApiV1ScimUsersOrgMembershipIdPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
