# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v1_auth_token_auth_identities_identity_id_get200_response_identity_token_auth import ApiV1AuthTokenAuthIdentitiesIdentityIdGet200ResponseIdentityTokenAuth  # noqa: E501

class TestApiV1AuthTokenAuthIdentitiesIdentityIdGet200ResponseIdentityTokenAuth(unittest.TestCase):
    """ApiV1AuthTokenAuthIdentitiesIdentityIdGet200ResponseIdentityTokenAuth unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1AuthTokenAuthIdentitiesIdentityIdGet200ResponseIdentityTokenAuth:
        """Test ApiV1AuthTokenAuthIdentitiesIdentityIdGet200ResponseIdentityTokenAuth
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1AuthTokenAuthIdentitiesIdentityIdGet200ResponseIdentityTokenAuth`
        """
        model = ApiV1AuthTokenAuthIdentitiesIdentityIdGet200ResponseIdentityTokenAuth()  # noqa: E501
        if include_optional:
            return ApiV1AuthTokenAuthIdentitiesIdentityIdGet200ResponseIdentityTokenAuth(
                id = '',
                access_token_ttl = 1.337,
                access_token_max_ttl = 1.337,
                access_token_num_uses_limit = 1.337,
                access_token_trusted_ips = None,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                identity_id = ''
            )
        else:
            return ApiV1AuthTokenAuthIdentitiesIdentityIdGet200ResponseIdentityTokenAuth(
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                identity_id = '',
        )
        """

    def testApiV1AuthTokenAuthIdentitiesIdentityIdGet200ResponseIdentityTokenAuth(self):
        """Test ApiV1AuthTokenAuthIdentitiesIdentityIdGet200ResponseIdentityTokenAuth"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
