# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v2_service_token_get200_response_user import ApiV2ServiceTokenGet200ResponseUser  # noqa: E501

class TestApiV2ServiceTokenGet200ResponseUser(unittest.TestCase):
    """ApiV2ServiceTokenGet200ResponseUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV2ServiceTokenGet200ResponseUser:
        """Test ApiV2ServiceTokenGet200ResponseUser
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV2ServiceTokenGet200ResponseUser`
        """
        model = ApiV2ServiceTokenGet200ResponseUser()  # noqa: E501
        if include_optional:
            return ApiV2ServiceTokenGet200ResponseUser(
                auth_methods = [
                    ''
                    ],
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                devices = None,
                email = '',
                first_name = '',
                last_name = '',
                mfa_methods = [
                    ''
                    ],
                v = 1.337,
                id = ''
            )
        else:
            return ApiV2ServiceTokenGet200ResponseUser(
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
        )
        """

    def testApiV2ServiceTokenGet200ResponseUser(self):
        """Test ApiV2ServiceTokenGet200ResponseUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
