# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v1_scim_groups_get200_response_resources_inner_meta import ApiV1ScimGroupsGet200ResponseResourcesInnerMeta  # noqa: E501

class TestApiV1ScimGroupsGet200ResponseResourcesInnerMeta(unittest.TestCase):
    """ApiV1ScimGroupsGet200ResponseResourcesInnerMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1ScimGroupsGet200ResponseResourcesInnerMeta:
        """Test ApiV1ScimGroupsGet200ResponseResourcesInnerMeta
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1ScimGroupsGet200ResponseResourcesInnerMeta`
        """
        model = ApiV1ScimGroupsGet200ResponseResourcesInnerMeta()  # noqa: E501
        if include_optional:
            return ApiV1ScimGroupsGet200ResponseResourcesInnerMeta(
                resource_type = ''
            )
        else:
            return ApiV1ScimGroupsGet200ResponseResourcesInnerMeta(
                resource_type = '',
        )
        """

    def testApiV1ScimGroupsGet200ResponseResourcesInnerMeta(self):
        """Test ApiV1ScimGroupsGet200ResponseResourcesInnerMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
