# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v1_secret_approval_requests_id_review_post200_response import ApiV1SecretApprovalRequestsIdReviewPost200Response  # noqa: E501

class TestApiV1SecretApprovalRequestsIdReviewPost200Response(unittest.TestCase):
    """ApiV1SecretApprovalRequestsIdReviewPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1SecretApprovalRequestsIdReviewPost200Response:
        """Test ApiV1SecretApprovalRequestsIdReviewPost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1SecretApprovalRequestsIdReviewPost200Response`
        """
        model = ApiV1SecretApprovalRequestsIdReviewPost200Response()  # noqa: E501
        if include_optional:
            return ApiV1SecretApprovalRequestsIdReviewPost200Response(
                review = infisicalapi_client.models._api_v1_secret_approval_requests__id__review_post_200_response_review._api_v1_secret_approval_requests__id__review_post_200_response_review(
                    id = '', 
                    status = '', 
                    request_id = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    reviewer_user_id = '', )
            )
        else:
            return ApiV1SecretApprovalRequestsIdReviewPost200Response(
                review = infisicalapi_client.models._api_v1_secret_approval_requests__id__review_post_200_response_review._api_v1_secret_approval_requests__id__review_post_200_response_review(
                    id = '', 
                    status = '', 
                    request_id = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    reviewer_user_id = '', ),
        )
        """

    def testApiV1SecretApprovalRequestsIdReviewPost200Response(self):
        """Test ApiV1SecretApprovalRequestsIdReviewPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
