# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v1_ldap_config_post_request import ApiV1LdapConfigPostRequest  # noqa: E501

class TestApiV1LdapConfigPostRequest(unittest.TestCase):
    """ApiV1LdapConfigPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1LdapConfigPostRequest:
        """Test ApiV1LdapConfigPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1LdapConfigPostRequest`
        """
        model = ApiV1LdapConfigPostRequest()  # noqa: E501
        if include_optional:
            return ApiV1LdapConfigPostRequest(
                organization_id = '',
                is_active = True,
                url = '',
                bind_dn = '',
                bind_pass = '',
                unique_user_attribute = 'uidNumber',
                search_base = '',
                search_filter = '(uid={{username}})',
                group_search_base = '',
                group_search_filter = '(|(memberUid={{.Username}})(member={{.UserDN}})(uniqueMember={{.UserDN}}))',
                ca_cert = ''
            )
        else:
            return ApiV1LdapConfigPostRequest(
                organization_id = '',
                is_active = True,
                url = '',
                bind_dn = '',
                bind_pass = '',
                search_base = '',
                group_search_base = '',
        )
        """

    def testApiV1LdapConfigPostRequest(self):
        """Test ApiV1LdapConfigPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
