# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v1_dynamic_secrets_post_request_provider_any_of_inputs import ApiV1DynamicSecretsPostRequestProviderAnyOfInputs  # noqa: E501

class TestApiV1DynamicSecretsPostRequestProviderAnyOfInputs(unittest.TestCase):
    """ApiV1DynamicSecretsPostRequestProviderAnyOfInputs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1DynamicSecretsPostRequestProviderAnyOfInputs:
        """Test ApiV1DynamicSecretsPostRequestProviderAnyOfInputs
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1DynamicSecretsPostRequestProviderAnyOfInputs`
        """
        model = ApiV1DynamicSecretsPostRequestProviderAnyOfInputs()  # noqa: E501
        if include_optional:
            return ApiV1DynamicSecretsPostRequestProviderAnyOfInputs(
                client = 'postgres',
                host = '',
                port = 1.337,
                database = '',
                username = '',
                password = '',
                creation_statement = '',
                revocation_statement = '',
                renew_statement = '',
                ca = ''
            )
        else:
            return ApiV1DynamicSecretsPostRequestProviderAnyOfInputs(
                client = 'postgres',
                host = '',
                port = 1.337,
                database = '',
                username = '',
                password = '',
                creation_statement = '',
                revocation_statement = '',
        )
        """

    def testApiV1DynamicSecretsPostRequestProviderAnyOfInputs(self):
        """Test ApiV1DynamicSecretsPostRequestProviderAnyOfInputs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
