# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v1_additional_privilege_identity_delete_request import ApiV1AdditionalPrivilegeIdentityDeleteRequest  # noqa: E501

class TestApiV1AdditionalPrivilegeIdentityDeleteRequest(unittest.TestCase):
    """ApiV1AdditionalPrivilegeIdentityDeleteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1AdditionalPrivilegeIdentityDeleteRequest:
        """Test ApiV1AdditionalPrivilegeIdentityDeleteRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1AdditionalPrivilegeIdentityDeleteRequest`
        """
        model = ApiV1AdditionalPrivilegeIdentityDeleteRequest()  # noqa: E501
        if include_optional:
            return ApiV1AdditionalPrivilegeIdentityDeleteRequest(
                privilege_slug = '0',
                identity_id = '0',
                project_slug = '0'
            )
        else:
            return ApiV1AdditionalPrivilegeIdentityDeleteRequest(
                privilege_slug = '0',
                identity_id = '0',
                project_slug = '0',
        )
        """

    def testApiV1AdditionalPrivilegeIdentityDeleteRequest(self):
        """Test ApiV1AdditionalPrivilegeIdentityDeleteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
