# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v1_integration_auth_integration_auth_id_teamcity_build_configs_get200_response_build_configs_inner import ApiV1IntegrationAuthIntegrationAuthIdTeamcityBuildConfigsGet200ResponseBuildConfigsInner  # noqa: E501

class TestApiV1IntegrationAuthIntegrationAuthIdTeamcityBuildConfigsGet200ResponseBuildConfigsInner(unittest.TestCase):
    """ApiV1IntegrationAuthIntegrationAuthIdTeamcityBuildConfigsGet200ResponseBuildConfigsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1IntegrationAuthIntegrationAuthIdTeamcityBuildConfigsGet200ResponseBuildConfigsInner:
        """Test ApiV1IntegrationAuthIntegrationAuthIdTeamcityBuildConfigsGet200ResponseBuildConfigsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1IntegrationAuthIntegrationAuthIdTeamcityBuildConfigsGet200ResponseBuildConfigsInner`
        """
        model = ApiV1IntegrationAuthIntegrationAuthIdTeamcityBuildConfigsGet200ResponseBuildConfigsInner()  # noqa: E501
        if include_optional:
            return ApiV1IntegrationAuthIntegrationAuthIdTeamcityBuildConfigsGet200ResponseBuildConfigsInner(
                name = '',
                build_config_id = ''
            )
        else:
            return ApiV1IntegrationAuthIntegrationAuthIdTeamcityBuildConfigsGet200ResponseBuildConfigsInner(
                name = '',
                build_config_id = '',
        )
        """

    def testApiV1IntegrationAuthIntegrationAuthIdTeamcityBuildConfigsGet200ResponseBuildConfigsInner(self):
        """Test ApiV1IntegrationAuthIntegrationAuthIdTeamcityBuildConfigsGet200ResponseBuildConfigsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
