# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v1_ldap_config_config_id_group_maps_post_request import ApiV1LdapConfigConfigIdGroupMapsPostRequest  # noqa: E501

class TestApiV1LdapConfigConfigIdGroupMapsPostRequest(unittest.TestCase):
    """ApiV1LdapConfigConfigIdGroupMapsPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1LdapConfigConfigIdGroupMapsPostRequest:
        """Test ApiV1LdapConfigConfigIdGroupMapsPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1LdapConfigConfigIdGroupMapsPostRequest`
        """
        model = ApiV1LdapConfigConfigIdGroupMapsPostRequest()  # noqa: E501
        if include_optional:
            return ApiV1LdapConfigConfigIdGroupMapsPostRequest(
                ldap_group_cn = '',
                group_slug = ''
            )
        else:
            return ApiV1LdapConfigConfigIdGroupMapsPostRequest(
                ldap_group_cn = '',
                group_slug = '',
        )
        """

    def testApiV1LdapConfigConfigIdGroupMapsPostRequest(self):
        """Test ApiV1LdapConfigConfigIdGroupMapsPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
