# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from infisicalapi_client.models.api_v1_secret_imports_post200_response import ApiV1SecretImportsPost200Response  # noqa: E501

class TestApiV1SecretImportsPost200Response(unittest.TestCase):
    """ApiV1SecretImportsPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1SecretImportsPost200Response:
        """Test ApiV1SecretImportsPost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1SecretImportsPost200Response`
        """
        model = ApiV1SecretImportsPost200Response()  # noqa: E501
        if include_optional:
            return ApiV1SecretImportsPost200Response(
                message = '',
                secret_import = infisicalapi_client.models._api_v1_secret_imports_get_200_response_secret_imports_inner._api_v1_secret_imports_get_200_response_secretImports_inner(
                    id = '', 
                    version = 1.337, 
                    import_path = '', 
                    position = 1.337, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    folder_id = '', 
                    is_replication = True, 
                    is_replication_success = True, 
                    replication_status = '', 
                    last_replicated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    is_reserved = True, 
                    import_env = infisicalapi_client.models._api_v1_secret_imports_get_200_response_secret_imports_inner_import_env._api_v1_secret_imports_get_200_response_secretImports_inner_importEnv(
                        name = '', 
                        slug = '', 
                        id = '', ), )
            )
        else:
            return ApiV1SecretImportsPost200Response(
                message = '',
                secret_import = infisicalapi_client.models._api_v1_secret_imports_get_200_response_secret_imports_inner._api_v1_secret_imports_get_200_response_secretImports_inner(
                    id = '', 
                    version = 1.337, 
                    import_path = '', 
                    position = 1.337, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    folder_id = '', 
                    is_replication = True, 
                    is_replication_success = True, 
                    replication_status = '', 
                    last_replicated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    is_reserved = True, 
                    import_env = infisicalapi_client.models._api_v1_secret_imports_get_200_response_secret_imports_inner_import_env._api_v1_secret_imports_get_200_response_secretImports_inner_importEnv(
                        name = '', 
                        slug = '', 
                        id = '', ), ),
        )
        """

    def testApiV1SecretImportsPost200Response(self):
        """Test ApiV1SecretImportsPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
