# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field
from infisicalapi_client.models.api_v1_secret_snapshot_secret_snapshot_id_get200_response_secret_snapshot import ApiV1SecretSnapshotSecretSnapshotIdGet200ResponseSecretSnapshot

class ApiV1SecretSnapshotSecretSnapshotIdGet200Response(BaseModel):
    """
    ApiV1SecretSnapshotSecretSnapshotIdGet200Response
    """
    secret_snapshot: ApiV1SecretSnapshotSecretSnapshotIdGet200ResponseSecretSnapshot = Field(default=..., alias="secretSnapshot")
    __properties = ["secretSnapshot"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ApiV1SecretSnapshotSecretSnapshotIdGet200Response:
        """Create an instance of ApiV1SecretSnapshotSecretSnapshotIdGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of secret_snapshot
        if self.secret_snapshot:
            _dict['secretSnapshot'] = self.secret_snapshot.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ApiV1SecretSnapshotSecretSnapshotIdGet200Response:
        """Create an instance of ApiV1SecretSnapshotSecretSnapshotIdGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ApiV1SecretSnapshotSecretSnapshotIdGet200Response.parse_obj(obj)

        _obj = ApiV1SecretSnapshotSecretSnapshotIdGet200Response.parse_obj({
            "secret_snapshot": ApiV1SecretSnapshotSecretSnapshotIdGet200ResponseSecretSnapshot.from_dict(obj.get("secretSnapshot")) if obj.get("secretSnapshot") is not None else None
        })
        return _obj


