# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conlist
from infisicalapi_client.models.api_v1_workspace_project_id_tags_get200_response_workspace_tags_inner import ApiV1WorkspaceProjectIdTagsGet200ResponseWorkspaceTagsInner

class ApiV1WorkspaceProjectIdTagsGet200Response(BaseModel):
    """
    ApiV1WorkspaceProjectIdTagsGet200Response
    """
    workspace_tags: conlist(ApiV1WorkspaceProjectIdTagsGet200ResponseWorkspaceTagsInner) = Field(default=..., alias="workspaceTags")
    __properties = ["workspaceTags"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ApiV1WorkspaceProjectIdTagsGet200Response:
        """Create an instance of ApiV1WorkspaceProjectIdTagsGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in workspace_tags (list)
        _items = []
        if self.workspace_tags:
            for _item in self.workspace_tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['workspaceTags'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ApiV1WorkspaceProjectIdTagsGet200Response:
        """Create an instance of ApiV1WorkspaceProjectIdTagsGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ApiV1WorkspaceProjectIdTagsGet200Response.parse_obj(obj)

        _obj = ApiV1WorkspaceProjectIdTagsGet200Response.parse_obj({
            "workspace_tags": [ApiV1WorkspaceProjectIdTagsGet200ResponseWorkspaceTagsInner.from_dict(_item) for _item in obj.get("workspaceTags")] if obj.get("workspaceTags") is not None else None
        })
        return _obj


