# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conlist
from infisicalapi_client.models.api_v1_identities_identity_id_identity_memberships_get200_response_identity_memberships_inner import ApiV1IdentitiesIdentityIdIdentityMembershipsGet200ResponseIdentityMembershipsInner

class ApiV1IdentitiesIdentityIdIdentityMembershipsGet200Response(BaseModel):
    """
    ApiV1IdentitiesIdentityIdIdentityMembershipsGet200Response
    """
    identity_memberships: conlist(ApiV1IdentitiesIdentityIdIdentityMembershipsGet200ResponseIdentityMembershipsInner) = Field(default=..., alias="identityMemberships")
    __properties = ["identityMemberships"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ApiV1IdentitiesIdentityIdIdentityMembershipsGet200Response:
        """Create an instance of ApiV1IdentitiesIdentityIdIdentityMembershipsGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in identity_memberships (list)
        _items = []
        if self.identity_memberships:
            for _item in self.identity_memberships:
                if _item:
                    _items.append(_item.to_dict())
            _dict['identityMemberships'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ApiV1IdentitiesIdentityIdIdentityMembershipsGet200Response:
        """Create an instance of ApiV1IdentitiesIdentityIdIdentityMembershipsGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ApiV1IdentitiesIdentityIdIdentityMembershipsGet200Response.parse_obj(obj)

        _obj = ApiV1IdentitiesIdentityIdIdentityMembershipsGet200Response.parse_obj({
            "identity_memberships": [ApiV1IdentitiesIdentityIdIdentityMembershipsGet200ResponseIdentityMembershipsInner.from_dict(_item) for _item in obj.get("identityMemberships")] if obj.get("identityMemberships") is not None else None
        })
        return _obj


