# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conlist
from infisicalapi_client.models.api_v1_integration_auth_integration_auth_id_github_envs_get200_response_envs_inner import ApiV1IntegrationAuthIntegrationAuthIdGithubEnvsGet200ResponseEnvsInner

class ApiV1IntegrationAuthIntegrationAuthIdGithubEnvsGet200Response(BaseModel):
    """
    ApiV1IntegrationAuthIntegrationAuthIdGithubEnvsGet200Response
    """
    envs: conlist(ApiV1IntegrationAuthIntegrationAuthIdGithubEnvsGet200ResponseEnvsInner) = Field(...)
    __properties = ["envs"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ApiV1IntegrationAuthIntegrationAuthIdGithubEnvsGet200Response:
        """Create an instance of ApiV1IntegrationAuthIntegrationAuthIdGithubEnvsGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in envs (list)
        _items = []
        if self.envs:
            for _item in self.envs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['envs'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ApiV1IntegrationAuthIntegrationAuthIdGithubEnvsGet200Response:
        """Create an instance of ApiV1IntegrationAuthIntegrationAuthIdGithubEnvsGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ApiV1IntegrationAuthIntegrationAuthIdGithubEnvsGet200Response.parse_obj(obj)

        _obj = ApiV1IntegrationAuthIntegrationAuthIdGithubEnvsGet200Response.parse_obj({
            "envs": [ApiV1IntegrationAuthIntegrationAuthIdGithubEnvsGet200ResponseEnvsInner.from_dict(_item) for _item in obj.get("envs")] if obj.get("envs") is not None else None
        })
        return _obj


