# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr

class ApiV1LdapConfigPatchRequest(BaseModel):
    """
    ApiV1LdapConfigPatchRequest
    """
    is_active: Optional[StrictBool] = Field(default=None, alias="isActive")
    url: Optional[StrictStr] = None
    bind_dn: Optional[StrictStr] = Field(default=None, alias="bindDN")
    bind_pass: Optional[StrictStr] = Field(default=None, alias="bindPass")
    unique_user_attribute: Optional[StrictStr] = Field(default=None, alias="uniqueUserAttribute")
    search_base: Optional[StrictStr] = Field(default=None, alias="searchBase")
    search_filter: Optional[StrictStr] = Field(default=None, alias="searchFilter")
    group_search_base: Optional[StrictStr] = Field(default=None, alias="groupSearchBase")
    group_search_filter: Optional[StrictStr] = Field(default=None, alias="groupSearchFilter")
    ca_cert: Optional[StrictStr] = Field(default=None, alias="caCert")
    organization_id: StrictStr = Field(default=..., alias="organizationId")
    __properties = ["isActive", "url", "bindDN", "bindPass", "uniqueUserAttribute", "searchBase", "searchFilter", "groupSearchBase", "groupSearchFilter", "caCert", "organizationId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ApiV1LdapConfigPatchRequest:
        """Create an instance of ApiV1LdapConfigPatchRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ApiV1LdapConfigPatchRequest:
        """Create an instance of ApiV1LdapConfigPatchRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ApiV1LdapConfigPatchRequest.parse_obj(obj)

        _obj = ApiV1LdapConfigPatchRequest.parse_obj({
            "is_active": obj.get("isActive"),
            "url": obj.get("url"),
            "bind_dn": obj.get("bindDN"),
            "bind_pass": obj.get("bindPass"),
            "unique_user_attribute": obj.get("uniqueUserAttribute"),
            "search_base": obj.get("searchBase"),
            "search_filter": obj.get("searchFilter"),
            "group_search_base": obj.get("groupSearchBase"),
            "group_search_filter": obj.get("groupSearchFilter"),
            "ca_cert": obj.get("caCert"),
            "organization_id": obj.get("organizationId")
        })
        return _obj


