# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime

from pydantic import BaseModel, Field, StrictStr

class ApiV1PasswordBackupPrivateKeyGet200ResponseBackupPrivateKey(BaseModel):
    """
    ApiV1PasswordBackupPrivateKeyGet200ResponseBackupPrivateKey
    """
    id: StrictStr = Field(...)
    encrypted_private_key: StrictStr = Field(default=..., alias="encryptedPrivateKey")
    iv: StrictStr = Field(...)
    tag: StrictStr = Field(...)
    algorithm: StrictStr = Field(...)
    key_encoding: StrictStr = Field(default=..., alias="keyEncoding")
    salt: StrictStr = Field(...)
    created_at: datetime = Field(default=..., alias="createdAt")
    updated_at: datetime = Field(default=..., alias="updatedAt")
    user_id: StrictStr = Field(default=..., alias="userId")
    __properties = ["id", "encryptedPrivateKey", "iv", "tag", "algorithm", "keyEncoding", "salt", "createdAt", "updatedAt", "userId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ApiV1PasswordBackupPrivateKeyGet200ResponseBackupPrivateKey:
        """Create an instance of ApiV1PasswordBackupPrivateKeyGet200ResponseBackupPrivateKey from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ApiV1PasswordBackupPrivateKeyGet200ResponseBackupPrivateKey:
        """Create an instance of ApiV1PasswordBackupPrivateKeyGet200ResponseBackupPrivateKey from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ApiV1PasswordBackupPrivateKeyGet200ResponseBackupPrivateKey.parse_obj(obj)

        _obj = ApiV1PasswordBackupPrivateKeyGet200ResponseBackupPrivateKey.parse_obj({
            "id": obj.get("id"),
            "encrypted_private_key": obj.get("encryptedPrivateKey"),
            "iv": obj.get("iv"),
            "tag": obj.get("tag"),
            "algorithm": obj.get("algorithm"),
            "key_encoding": obj.get("keyEncoding"),
            "salt": obj.get("salt"),
            "created_at": obj.get("createdAt"),
            "updated_at": obj.get("updatedAt"),
            "user_id": obj.get("userId")
        })
        return _obj


