# coding: utf-8

"""
    Infisical API

    List of all available APIs that can be consumed

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, validator
from infisicalapi_client.models.api_v3_auth_login2_post200_response_any_of import ApiV3AuthLogin2Post200ResponseAnyOf
from infisicalapi_client.models.api_v3_auth_login2_post200_response_any_of1 import ApiV3AuthLogin2Post200ResponseAnyOf1
from typing import Union, Any, List, TYPE_CHECKING
from pydantic import StrictStr, Field

APIV3AUTHLOGIN2POST200RESPONSE_ANY_OF_SCHEMAS = ["ApiV3AuthLogin2Post200ResponseAnyOf", "ApiV3AuthLogin2Post200ResponseAnyOf1"]

class ApiV3AuthLogin2Post200Response(BaseModel):
    """
    ApiV3AuthLogin2Post200Response
    """

    # data type: ApiV3AuthLogin2Post200ResponseAnyOf
    anyof_schema_1_validator: Optional[ApiV3AuthLogin2Post200ResponseAnyOf] = None
    # data type: ApiV3AuthLogin2Post200ResponseAnyOf1
    anyof_schema_2_validator: Optional[ApiV3AuthLogin2Post200ResponseAnyOf1] = None
    if TYPE_CHECKING:
        actual_instance: Union[ApiV3AuthLogin2Post200ResponseAnyOf, ApiV3AuthLogin2Post200ResponseAnyOf1]
    else:
        actual_instance: Any
    any_of_schemas: List[str] = Field(APIV3AUTHLOGIN2POST200RESPONSE_ANY_OF_SCHEMAS, const=True)

    class Config:
        validate_assignment = True

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = ApiV3AuthLogin2Post200Response.construct()
        error_messages = []
        # validate data type: ApiV3AuthLogin2Post200ResponseAnyOf
        if not isinstance(v, ApiV3AuthLogin2Post200ResponseAnyOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ApiV3AuthLogin2Post200ResponseAnyOf`")
        else:
            return v

        # validate data type: ApiV3AuthLogin2Post200ResponseAnyOf1
        if not isinstance(v, ApiV3AuthLogin2Post200ResponseAnyOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ApiV3AuthLogin2Post200ResponseAnyOf1`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in ApiV3AuthLogin2Post200Response with anyOf schemas: ApiV3AuthLogin2Post200ResponseAnyOf, ApiV3AuthLogin2Post200ResponseAnyOf1. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> ApiV3AuthLogin2Post200Response:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> ApiV3AuthLogin2Post200Response:
        """Returns the object represented by the json string"""
        instance = ApiV3AuthLogin2Post200Response.construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[ApiV3AuthLogin2Post200ResponseAnyOf] = None
        try:
            instance.actual_instance = ApiV3AuthLogin2Post200ResponseAnyOf.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[ApiV3AuthLogin2Post200ResponseAnyOf1] = None
        try:
            instance.actual_instance = ApiV3AuthLogin2Post200ResponseAnyOf1.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ApiV3AuthLogin2Post200Response with anyOf schemas: ApiV3AuthLogin2Post200ResponseAnyOf, ApiV3AuthLogin2Post200ResponseAnyOf1. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_dict()
        else:
            return json.dumps(self.actual_instance)

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.dict())


